CREATE TABLE APP(
    APP_NAME VARCHAR(20),
    DOMAIN_ID VARCHAR(10) not null,
    WEBSITE_URL VARCHAR(100) not null,
    ADMIN_ID VARCHAR(10) ,
    CUSTOMER_ID VARCHAR(10),
    PRIMARY KEY(DOMAIN_ID)
);
CREATE TABLE CUSTOMERS(
    C_ID VARCHAR(10) NOT NULL,
    USER_NAME VARCHAR(20) ,
    PASS VARCHAR(10),
    MOBILE_NO VARCHAR(15),
    EMAIL VARCHAR(20),
    COUNTRY VARCHAR(15),
    ADDRESS TEXT,
    DOMAIN_ID VARCHAR(10),
    PRIMARY KEY(C_ID),
    FOREIGN KEY(DOMAIN_ID) REFERENCES APP
);
CREATE TABLE PAYMENT(
    PAYMENT_ID VARCHAR(15),
    AMOUNT INT,
    PAYMENT_MODE VARCHAR(10),
    PAYMENT_TIME TIME,
    PRIMARY KEY(PAYMENT_ID),
    ADMIN_ID VARCHAR(10),
    FOREIGN KEY(ADMIN_ID) REFERENCES CUSTUMERS
);
CREATE TABLE MAKE_PAYMENT(
    C_ID VARCHAR(10),
    PAYMENT_ID VARCHAR(15),
    PRIMARY KEY (C_ID,PAYMENT_ID),
    FOREIGN KEY(C_ID) REFERENCES CUSTOMERS,
    FOREIGN KEY(PAYMENT_ID) REFERENCES PAYMENT
);
CREATE TABLE CART(
    CART_ID VARCHAR(10),
    NO_OF_PRODUCTS INT,
    TOTAL_PRICE INT,
    PRIMARY KEY(CART_ID),
    CUSTOMER_ID VARCHAR(10),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS
);
CREATE TABLE ADMINISTRATION(
    ADMIN_ID VARCHAR(10) NOT NULL,
    PASSWORD VARCHAR(20),
    DETAILS TEXT,
    DOMAIN_ID VARCHAR(10) ,
    FOREIGN KEY(DOMAIN_ID) REFERENCES APP
);
CREATE TABLE MOBILES(
    MOBILE_ID VARCHAR(20) NOT NULL,
    MODEL_NO VARCHAR(20),
    COMPANY_NAME VARCHAR(20),
    AVAIL INT,
    PRIMARY KEY(MOBILE_ID)
);
CREATE TABLE CAMERA(
    CAMERA_ID VARCHAR(10) NOT NULL,
    MACROLENS VARCHAR(10),
    MAINCAMERA VARCHAR(10),
    ULTRAWIDE VARCHAR(10),
    IOS VARCHAR(3),
    SENSOR_NO VARCHAR(10),
    PRIMARY KEY(CAMERA_ID)
);
CREATE TABLE PROCESSOR(
    PROCESSOR_ID VARCHAR(10) NOT NULL,
    PROCESSOR_TYPE VARCHAR(10),
    PRIMARY_CLOCK_SPEED INT,
    SEC_CLOCK_SPEED INT,
    NO_OF_CORE INT,
    NO_OF_THREADS INT
    PRIMARY KEY(PROCESSOR_ID)
);
CREATE TABLE SMART_PHONE(
    MODEL_NO VARCHAR(15) NOT NULL,
    RAM INT,
    ROM INT,
    CONECTIVITY VARCHAR(10),
    BATTERY INT,
    PRICE INT,
    PROCESSOR_ID VARCHAR(20),
    CAMERA_ID VARCHAR(20),
    PRIMARY KEY(MODEL_NO),
    FOREIGN KEY(PROCESSOR_ID) REFERENCES PROCESSOR,
    FOREIGN KEY(CAMERA_ID) REFERENCES CAMERA
);
CREATE TABLE KEYPAD_MOBILE(
    MODEL_NO VARCHAR(15) NOT NULL,
    BATTERY INT,
    NO_OF_SIMS INT,
    ABOUT TEXT
);



